apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/02-distributed-tracing-uiplugin.yaml
  - resources/02-minio-tempo-storage.yaml
  - resources/03-tempostack.yaml
  - resources/04-otel-collector.yaml
  - resources/05-observability-and-grafana.yaml
  - resources/06-grafana-dashboard-configmaps.yaml
  - resources/07-tempostack-predelete-hook.yaml
