apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/01-namespaces.yaml
  - resources/02-minio-tempo-storage.yaml
  - resources/03-tempostack.yaml
  - resources/04-otel-collector.yaml
