apiVersion: v1
kind: Namespace
metadata:
  name: tempo-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: tempo-operator-group
  namespace: tempo-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - tempo-operator-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo-product
  namespace: tempo-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
