# Namespace for RHCL Observability components
apiVersion: v1
kind: Namespace
metadata:
  name: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    name: rhcl-observability
---
# Namespace for OpenTelemetry Collector
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    name: opentelemetry
