apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: rhcl-ai-gw
  namespace: openshift-ingress
  labels:
    kuadrant.io/gateway: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  gatewayClassName: istio
  listeners:
    - name: http-ai
      port: 80
      protocol: HTTP
      hostname: ai.example.com
      allowedRoutes:
        namespaces:
          from: All
    - name: https-ai-sandbox
      port: 443
      protocol: HTTPS
      hostname: ai.example.com
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: cert-manager-ingress-cert
      allowedRoutes:
        namespaces:
          from: All

