apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhcl-gw-public-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  secretName: rhcl-gw-public-tls
  dnsNames:
    - rhcl-workshop.example.com
    - oidc-rhcl-workshop.example.com
    - mcp.example.com
    - external.example.com
    - external-api.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod

