apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhcl-gw-oidc
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "18"
spec:
  host: oidc-rhcl-workshop.example.com
  to:
    kind: Service
    name: rhcl-gw-istio
  port:
    targetPort: 443
  tls:
    termination: passthrough

