apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/01-gateway.yaml
  - resources/02-mcpgatewayextension.yaml
  - resources/03-dnspolicy.yaml
  - resources/04-tlspolicy.yaml
  - resources/05-test-server-deployment.yaml
  - resources/06-httproutes.yaml
  - resources/07-mcpserverregistration.yaml
