apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: ai-bot-espn
  namespace: rhcl-ai-bot
  annotations:
    argocd.argoproj.io/sync-wave: "26"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  toolPrefix: ""
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ai-bot-mcp-server
  path: /mcp
