apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-mcp-to-ai-bot
  namespace: rhcl-ai-bot
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: mcp-system
  to:
    - group: ""
      kind: Service
