apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhcl-gw-external-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  secretName: rhcl-gw-external-sandbox-tls
  dnsNames:
    - external-api.REPLACE_ME_EXTERNAL_BASE_DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
