apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../full-install
  - ../rhcl2-mcp-gateway
  - mcp-vanity.yaml
  - tempo-minio.yaml
  - tracing-console.yaml
  - tls-policies.yaml
  - istio-telemetry-gateways.yaml
  - otel-collector.yaml
  - certificate-external-sandbox.yaml
  - gateway-public-certificate.yaml

patches:
  - path: patch-rhcl2-values.yaml
  - path: istio-tracing.yaml

