apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ui.yaml
  - resources/demo-api.yaml
  - resources/oidc-ui.yaml
  - resources/oidc-callback.yaml
  - resources/ai-bot.yaml
  - resources/external-proxy.yaml
  - resources/ab-canary.yaml
  - resources/keycloak.yaml
  - resources/ui-configmap.yaml
  - resources/oidc-ui-configmap.yaml
  - resources/oidc-callback-configmap.yaml
