apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ui.yaml
  - resources/demo-api.yaml
  - resources/oidc-ui.yaml
  - resources/oidc-callback.yaml
  - resources/ai-bot.yaml
  - resources/external-proxy.yaml
  - resources/ab-canary.yaml
  - resources/keycloak.yaml

configMapGenerator:
  - name: rhcl-ui
    namespace: demo
    files:
      - index.html=ui/index.html
  - name: rhcl-oidc-ui
    namespace: rhcl-oidc-portal
    files:
      - index.html=oidc-ui/index.html
  - name: oidc-callback
    namespace: rhcl-oidc-portal
    files:
      - server.js=oidc-callback/server.js

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
