apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-upstream-test

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - mcpserverregistration.yaml
