# Certificate for external-api domain (different DNS zone from apps.cluster)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhcl-gw-external-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  secretName: rhcl-gw-external-sandbox-tls
  dnsNames:
    - external-api.REPLACE_ME_EXTERNAL_BASE_DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
---
# Certificate for oidc domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhcl-gw-oidc-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  secretName: rhcl-gw-oidc-sandbox-tls
  dnsNames:
    - oidc-rhcl-workshop.REPLACE_ME_EXTERNAL_BASE_DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
---
# Certificate for mcp domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhcl-gw-mcp-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  secretName: rhcl-gw-mcp-sandbox-tls
  dnsNames:
    - mcp.REPLACE_ME_EXTERNAL_BASE_DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
---
# Certificate for ai domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhcl-gw-ai-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  secretName: rhcl-gw-ai-sandbox-tls
  dnsNames:
    - ai.REPLACE_ME_EXTERNAL_BASE_DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
