apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: rhcl-workshop-main-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-workshop-gw
    sectionName: https-main-public
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
---
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: rhcl-workshop-oidc-public-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-workshop-gw
    sectionName: https-oidc-public
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
---
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: rhcl-external-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-external-gw
    sectionName: https-external-public
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
---
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: rhcl-ai-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-ai-gw
    sectionName: https-ai-sandbox
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
---
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: rhcl-mcp-sandbox-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-mcp-gw
    sectionName: https-mcp-public
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
