apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-app-0-upstream-sample
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/demo-rhcl.git
    targetRevision: feature/split-applications
    path: gitops/apps/rhcl-demo-split/app-0-upstream-sample
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
