apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-app-2-platform-crs
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/demo-rhcl.git
    targetRevision: feature/apps345-espn-tools-verified
    path: gitops/apps/rhcl-demo-split/app-2-platform-crs
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
