apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-app-4-demo-apps
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/demo-rhcl.git
    targetRevision: feature/observability-implementation
    path: gitops/apps/rhcl-demo-split/app-4-demo-apps
    kustomize:
      patches:
        - target:
            group: apps
            version: v1
            kind: Deployment
            name: rhcl-ai-bot
            namespace: rhcl-ai-bot
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/env/8/value
              value: https://external-api.sandbox2689.opentlc.com
            - op: replace
              path: /spec/template/spec/containers/0/env/9/value
              value: http://mcp.sandbox2689.opentlc.com
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: rhcl-ai-bot
      namespace: rhcl-ai-bot
      jqPathExpressions:
        - .spec.template.spec.containers[].image
    - group: ""
      kind: ConfigMap
      name: rhcl-ui
      namespace: demo
      jqPathExpressions:
        - .data
    - group: ""
      kind: ConfigMap
      name: rhcl-oidc-ui
      namespace: rhcl-oidc-portal
      jqPathExpressions:
        - .data
    - group: ""
      kind: ConfigMap
      name: oidc-callback
      namespace: rhcl-oidc-portal
      jqPathExpressions:
        - .data
