apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-app-0-kuadrant-observability
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kuadrant/kuadrant-operator
    targetRevision: v1.3.0
    path: config/install/configure/observability
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
