apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-app-6-observability
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/demo-rhcl.git
    targetRevision: feature/apps345-espn-tools-verified
    path: gitops/apps/rhcl-demo-split/app-6-observability
  destination:
    server: https://kubernetes.default.svc
    namespace: rhcl-observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  ignoreDifferences:
    - group: tempo.grafana.com
      kind: TempoStack
      jqPathExpressions:
        - .status
    - group: opentelemetry.io
      kind: OpenTelemetryCollector
      jqPathExpressions:
        - .status
    - group: grafana.integreatly.org
      kind: Grafana
      jqPathExpressions:
        - .status
    - group: grafana.integreatly.org
      kind: GrafanaDatasource
      jqPathExpressions:
        - .status
    - group: grafana.integreatly.org
      kind: GrafanaDashboard
      jqPathExpressions:
        - .status
