apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-platform-crs-test
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/demo-rhcl.git
    targetRevision: feature/split-applications
    path: gitops/apps/rhcl-demo-split/app-2-platform-crs
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
