---
apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPGatewayExtension
metadata:
  name: mcp-gateway-extension
  namespace: mcp-system
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: mcp-gateway
    namespace: openshift-ingress
    sectionName: http-mcp
  publicHost: mcp.sandbox2689.opentlc.com
  privateHost: mcp-gateway-istio.openshift-ingress.svc.cluster.local:80
