---
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: mcp-gateway-dns
  namespace: mcp-system
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: mcp-gateway
    sectionName: http-mcp
  providerRefs:
    - name: aws-credentials
