---
apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: test-server1
  namespace: mcp-system
  labels:
    mcp.kuadrant.io/managed: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "27"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  path: /mcp
  toolPrefix: test1_
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-server1-route
