apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../appsets/mcp

patches:
  - path: patch-rhcl2-mcp-gateway-values.yaml
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: rhcl-mcp-gw
      namespace: openshift-ingress
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: istio
      - op: replace
        path: /spec/listeners/0/hostname
        value: REPLACE_ME_MCP_HOSTNAME
      - op: replace
        path: /spec/listeners/1/hostname
        value: REPLACE_ME_MCP_HOSTNAME

